portfolio/fatima_portfolio/urls.py
from django.urls import path
from . import views

app_name = 'fatima_portfolio'
urlpatterns = [
    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path("resume/", views.resume, name='resume')
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fatima_portfolio/', include('fatima_portfolio.urls')),
]

portfolio/fatima_portfolio/models.py
from django.db import models

# Create your models here.

portfolio/fatima_portfolio/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'fatima_portfolio/index.html')
def about(request):
    return render(request, 'fatima_portfolio/about.html')
def resume(request):
    return render(request, 'fatima_portfolio/resume.html')

portfolio/fatima_portfolio/templates/fatima_portfolio/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'fatima_portfolio/styles.css' %}" rel ="stylesheet">
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Include jQuery and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>

    <!-- Include Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>    <title>portfolio</title>
    <link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/128/3476/3476457.png">
</head>
<body style="background-color: #B3A59A;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'fatima_portfolio:index' %}">Fatima Anees Mulla</a>
        </div>
        <div class ="container-fluid nav justify-content-end">
            <ul class = "m-3 nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'fatima_portfolio:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'fatima_portfolio:about' %}">About</a>
                  </li>        
            </ul>
      </nav>
    
<div style="padding-left: 20px;" >
    <h1>About Me</h1>
        <p>
            Hello! I'm Fatima, a sophomore in AIML Engineering. Passionate about artificial intelligence and machine learning, I am constantly exploring new ways to apply these technologies to real-world problems.
        </p>
        <p>
            Currently pursuing my undergraduate degree, I have a strong foundation in algorithms and data structures. I am enthusiastic about leveraging AI to make a positive impact on society.
        </p>
    <h2>Skills</h2>
        <ul>
            <li>Programming Languages: Python, C, Java</li>
            <li>Machine Learning Libraries: Numpy, Pandas, Scikit-Learn</li>
            <li>Web Development: HTML, CSS, JavaScript</li>
        </ul>
    
    <div class="d-flex justify-content-center">
        <h2>RESUME</h2>
        <a href="{% url 'fatima_portfolio:resume' %}"><img src ="https://cdn-icons-png.flaticon.com/512/1250/1250696.png" width = 40px></a>
    </div>
    </div>
    
</body>
</html>

portfolio/fatima_portfolio/templates/fatima_portfolio/index.html
{% extends 'fatima_portfolio/layout.html' %}
{% load static %}
{% block body %}

<div class="container text-center" >
    <div class="row align-items-center">  
      <div class="col clearfix">
        <h1>Hi, I'm Fatima, a student from Bengaluru.</h1>
      </div>
      <div class="col">
        <img src = "{% static 'fatima_portfolio/images/p1.png'%}" class="img-fluid" alt="girl">
      </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<div id="carouselExample" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <!-- Slide 1 -->
        <div class="carousel-item active">
            <img src="{% static 'fatima_portfolio/images/gardenIoT.png'%}" class="d-block w-100" alt="First Slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Smart Garden</h5>
                <p>IoT based plant monitoring</p>
            </div>
        </div>
        <!-- Slide 2 -->
        <div class="carousel-item">
            <img src="{% static 'fatima_portfolio/images/yoga_ai.png'%}" class="d-block w-100" alt="Second Slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Yoga AI</h5>
                <p>Yoga Pose classifier using OpenCV human pose estimation</p>
            </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item">
            <a href="https://github.com/tessara77/rpa_sms_bot"><img src="{% static 'fatima_portfolio/images/smsRPA.png'%}" class="d-block w-100" alt="Third Slide"></a>
            <div class="carousel-caption d-none d-md-block">
                <h5>Student Management System</h5>
                <p>Robotic Process Automation using Automation Anywhere 360</p>
            </div>
        </div>
    </div>

    <!-- Carousel Controls -->
    <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<style>
    body {
            min-height: 100vh; 
            margin: 0;
        }

        .centered-div {
            text-align: center;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 8px;
            background-color: #f8f9fa;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh; 
        }
</style>
<div class="centered-div" id="contact" style = "background-color: #B3A59A;">
    <h2>Get in Touch</h2>
    <p>Have a question or want to collaborate? Feel free to <a href="mailto:pf4t1m4@gmail.com">email me</a>.</p>
</div>

{% endblock %}

#433a35

portfolio/fatima_portfolio/templates/fatima_portfolio/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'fatima_portfolio/styles.css' %}" rel ="stylesheet">
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Include jQuery and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>

    <!-- Include Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>    <title>portfolio</title>
    <link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/128/3476/3476457.png">
</head>
<body style="background-color: #B3A59A;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'fatima_portfolio:index' %}">Fatima Anees Mulla</a>
        </div>
        <div class ="container-fluid nav justify-content-end">
            <ul class = "m-3 nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'fatima_portfolio:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'fatima_portfolio:about' %}">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#carouselExample">Projects</a>
                  </li>    
                  <li class="nav-item">
                    <a class="nav-link" href="#contact">Contact</a>
                  </li>            
            </ul>
      </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

portfolio/fatima_portfolio/templates/fatima_portfolio/resume.html
{% extends 'fatima_portfolio/layout.html' %}
{% load static %}
{% block body %}
<div class="d-flex justify-content-center">
    <h1>RESUME</h1>
</div>
<iframe src="{% static 'fatima_portfolio/resume.pdf' %}" width="100%" height="800px"></iframe>

{% endblock %}